Updated Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -1,123 +1,105 @@
 pipeline {
     agent any
-    environment {
-        NEXUS_USER = credentials('nexus-username')
-        NEXUS_PASSWORD = credentials('nexus-password')
-        NEXUS_REPO = credentials('nexus-repo')
-    }
     stages {
-        stage('Code analisys stage') {
+        stage('Code Checkout') {
             steps {
-                withSonarQubeEnv('sonarqube') {
-                    sh 'mvn sonar:sonar'
+                git branch: 'main',
+                credentialsId: 'git-cred',
+                url: 'https://github.com/olufemi29/usteam.git'
+            }
+        }
+        stage('Code Analysis') {
+            steps {
+               withSonarQubeEnv('sonarqube') {
+                  sh "mvn sonar:sonar"
+               }
+            }
+        }
+        stage("Quality Gate") {
+            steps {
+              timeout(time: 2, unit: 'MINUTES') {
+                waitForQualityGate abortPipeline: true
+              }
+            }
+        }
+        stage('Dependency check') {
+            steps {
+                withCredentials([string(credentialsId: 'nvd-key', variable: 'NVD_API_KEY')]) {
+                    dependencyCheck additionalArguments: "--scan ./ --disableYarnAudit --disableNodeAudit --nvdApiKey $NVD_API_KEY",
+                        odcInstallation: 'DP-Check'
                 }
-            }
-        }
-        stage('Quality gate') {
-            steps {
-                timeout(time: 2, unit: 'MINUTES') {
-                    waitForQualityGate abortPipeline: true 
-                }
-            }
-        }
-        stage('Build artefacts') {
-            steps {
-                sh 'mvn clean install -DskipTests -Dcheckstyle.skip'
-            }
-        }
-        stage('OWASP Dependency Scan') {
-            steps {
-                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
                 dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
             }
         }
-        stage('Build Docker image') {
+        stage('Install Checkov') {
             steps {
-                sh 'docker build -t $NEXUS_REPO/myapp .'
+                sh '''
+                sudo yum install -y python3 python3-pip
+                # Upgrade pip and install Checkov
+                python3 -m pip install --upgrade pip
+                python3 -m pip install checkov --quiet
+                # Add Checkov to PATH
+                export PATH=$PATH:$(python3 -m site --user-base)/bin
+                # Verify Checkov installation
+                checkov --version || echo "Checkov installation failed"
+                '''
             }
         }
-        stage('Push artifacts to nexus-repo') {
+       stage('Infrastructure Security Scan') {
+            steps {
+                sh '''
+                    # Ensure correct PATH for Checkov command
+                    export PATH=$PATH:$(python3 -m site --user-base)/bin
+                    # Run Checkov scan on the repository
+                    checkov -d . --output cli || true
+                '''
+            }
+        }
+        stage('Build Artifact') {
+            steps {
+                sh 'mvn -f pom.xml clean package -DskipTests -Dcheckstyle.skip'
+            }
+        }
+        stage('Push Artifact to Nexus Repo') {
             steps {
                 nexusArtifactUploader artifacts: [[artifactId: 'spring-petclinic',
                 classifier: '',
                 file: 'target/spring-petclinic-2.4.2.war',
                 type: 'war']],
-                credentialsId: 'nexus-creds',
+                credentialsId: 'nexus-cred',
                 groupId: 'Petclinic',
-                nexusUrl: 'nexus.traveldeals.tech',
+                nexusUrl: 'nexus.selfdevops.space',
                 nexusVersion: 'nexus3',
                 protocol: 'https',
                 repository: 'nexus-repo',
                 version: '1.0'
             }
         }
-        stage('Trivy file scan') {
+        stage('Build docker image') {
             steps {
-                sh "trivy fs . > trivyfs.txt"
+                sshagent (['ansible-key']) {
+                      // Install Docker collection first
+                      sh 'ssh -t -t ec2-user@13.36.233.113 -o strictHostKeyChecking=no "ansible-galaxy collection install community.docker"'
+                      sh 'ssh -t -t ec2-user@13.36.233.113 -o strictHostKeyChecking=no "cd /etc/ansible && ansible-playbook /opt/docker/docker-image.yml"'
+                  }
+              }
+        }
+        stage('Trivy image scan') {
+            steps {
+               sh "trivy image cloudhight/testapp > trivyfs.txt"
             }
         }
-        stage('Login to Nexus repo') {
+        stage('Trigger Ansible to deploy app') {
             steps {
-                sh 'docker login --username $NEXUS_USER --password $NEXUS_PASSWORD $NEXUS_REPO'
-            }
+                sshagent (['ansible-key']) {
+                      sh 'ssh -t -t ec2-user@13.36.233.113 -o strictHostKeyChecking=no "cd /etc/ansible && ansible-playbook /opt/docker/docker-container.yml"'
+                      sh 'ssh -t -t ec2-user@13.36.233.113 -o strictHostKeyChecking=no "cd /etc/ansible && ansible-playbook /opt/docker/newrelic-container.yml"'
+                  }
+              }
         }
-        stage('Push image to Nexus repo') {
+        stage('slack notification') {
             steps {
-                sh 'docker push $NEXUS_REPO/myapp'
-            }
-        }
-        stage('Trivi image scan') {
-            steps {
-                sh "trivy image $NEXUS_REPO/myapp > trivy.txt"
-            }
-        }
-        stage('Deploy to stage') {
-            steps {
-                sshagent(['ansible-key']) {
-                    sh 'ssh -t -t ec2-user@10.0.3.215 -o strictHostKeyChecking=no "ansible-playbook -i /etc/ansible/stage_hosts /etc/ansible/deployment.yml"'
-                }
-            }
-        }
-        stage('check stage website availability') {
-            steps {
-                 sh "sleep 90"
-                 sh "curl -s -o /dev/null -w \"%{http_code}\" https://stage.traveldeals.tech"
-                script {
-                    def response = sh(script: "curl -s -o /dev/null -w \"%{http_code}\" https://stage.traveldeals.tech", returnStdout: true).trim()
-                    if (response == "200") {
-                        slackSend(color: 'good', message: "The stage petclinic website is up and running with HTTP status code ${response}.", tokenCredentialId: 'slack')
-                    } else {
-                        slackSend(color: 'danger', message: "The stage petclinic wordpress website appears to be down with HTTP status code ${response}.", tokenCredentialId: 'slack')
-                    }
-                }
-            }
-        }
-        stage('Request for Approval') {
-            steps {
-                timeout(activity: true, time: 10) {
-                    input message: 'Needs Approval ', submitter: 'admin'
-                }
-            }
-        }
-        stage('Deploy to prod') {
-            steps {
-                sshagent(['ansible-key']) {
-                    sh 'ssh -t -t ec2-user@10.0.3.215 -o strictHostKeyChecking=no "ansible-playbook -i /etc/ansible/prod_hosts /etc/ansible/deployment.yml"'
-                }
-            }
-        }
-        stage('check prod website availability') {
-            steps {
-                 sh "sleep 90"
-                 sh "curl -s -o /dev/null -w \"%{http_code}\" https://prod.traveldeals.tech"
-                script {
-                    def response = sh(script: "curl -s -o /dev/null -w \"%{http_code}\" https://prod.traveldeals.tech", returnStdout: true).trim()
-                    if (response == "200") {
-                        slackSend(color: 'good', message: "The prod petclinic website is up and running with HTTP status code ${response}.", tokenCredentialId: 'slack')
-                    } else {
-                        slackSend(color: 'danger', message: "The prod petclinic wordpress website appears to be down with HTTP status code ${response}.", tokenCredentialId: 'slack')
-                    }
-                }
+                slackSend channel: '24th-february-jenkins-pipeline-project-us-team', message: 'Application deploy successfully ', teamDomain: 'Cloudhight', tokenCredentialId: 'slack-cred'
             }
         }
     }
